# docker compose up
# docker exec -it hadoop bash
version: "3.9"
services:
  hadoop-dev:
    container_name: hadoop
    image: hibuz/hadoop-dev
    ports:
      - 9870:9870
    #command: yarn
    volumes:
      - hadoop-vol:/tmp
      - .:/home/hadoop/hadoop-example:rw

volumes:
  hadoop-vol: {}
